sudo: false
language: ruby
rvm:
- 2.6.5
before_install: gem install bundler
notifications:
  slack:
    secure: asLqe46poNqwGYHVOiftb8kyxOsriVq1t/MZZIhSChd2VmZOcydaTvu0wEILQA42/RkArt4VR3OlplqPjxrCbxNuAPYBJoir0e/0LvL7DP5K43Ufa8m4WS+MBpBBTNqm8H2MKMtRPN64YWOlrTVOCdS8XvviKZGh1+TQz+/VLkg=
